version: "3.8"
services:
  local-spark:
    image: local-spark
    container_name: local-spark
    build:
      context: ./container/spark
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - METADATE_DRIVERNAME=postgresql
      - METADATA_HOST=metadata
      - METADATA_PORT=5432
      - METADATA_USERNAME=sdeuser
      - METADATA_PASSWORD=sdepassword
      - METADATA_DATABASE=metadatadb
    volumes:
      - ./container/sparks-default.conf:/usr/local/lib/python3.11/site-packages/pyspark/conf/spark-defaults.conf
      - .:/opt/spark-playground


#  spark-worker-1:
#    image: docker.io/bitnami/spark3.4
#    container_name: "spark-worker-1"
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=2G
#      - SPARK_WORKER_CORES=1
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    networks:
#      - spark_network

#  spark-worker-2:
#    image: docker.io/bitnami/spark3.4
#    container_name: "spark-worker-2"
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=2G
#      - SPARK_WORKER_CORES=1
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    networks:
#      - spark_network
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123

  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc rm -r --force myminio/sparkplayground; /usr/bin/mc mb myminio/sparkplayground; /usr/bin/mc policy download myminio/sparkplayground; exit 0; "
    depends_on:
      - minio

  metadata:
    image: postgres:15
    container_name: metadata
    depends_on:
      - minio
    environment:
      - POSTGRES_USER=sdeuser
      - POSTGRES_PASSWORD=sdepassword
      - POSTGRES_DB=metadatadb
    ports:
      - "5432:5432"
